# 数据库配置
install_path = "/data"                     # 安装路径（绝对路径，如果为空则使用数据库用户的家目录作为 install_path）
yasdb_home = "./yasdb_home"                # 家目录（默认为相对路径，拼接到 install_path，可以指定绝对路径）
yasdb_data = "./yasdb_data"                # 数据目录（默认为相对路径，拼接到 install_path，可以指定绝对路径）
yasdb_back = "./yasdb_back"                # 备份目录（默认为相对路径，拼接到 install_path，可以指定绝对路径）
yasdb_back_subdirs = ["archive", "backup"] # 备份子目录，拼接到 yasdb_back

# =================================================================================================
# 其他主机列表
# 用于测试SSH连通性，如果不填写，会自动跳过SSH连接测试

# 主机一
# [[hosts]]
# ip = ""       # 主机IP
# user = ""     # 登录用户
# password = "" # 登录密码
# port = 22     # SSH端口

# 主机二
# [[hosts]]
# ip = ""       # 主机IP
# user = ""     # 登录用户
# password = "" # 登录密码
# port = 22     # SSH端口

# ......
# =================================================================================================
